Repository SIRI-CEN/SIRI, pull requests merged in 2025-05, with the labels that each got.

#114 add coordinates to FacilityLocation
  examples/siri_exm_FM/exf_facilityMonitoring_response.xml
  xsd/siri_model/siri_facility.xsd
Labels: enhancement, needs documentation update

#141 SituationExchange - add FacilityLocation to AffectedFacilityStructure
  xsd/siri_model/siri_situationAffects.xsd
Labels: enhancement, SX

#160 Add example for DataSource in ET
  examples/siri_exm_ET/ext_estimatedTimetable_response.xml
Labels: ET
